### ISSUE TITLE
Consider using generic sharding hasher

### ISSUE THREAD

**Issue by Yiling-J** [erni27/imcache#32]
Currently there is only one hasher: `DefaultStringHasher64`, it's possible to generate hash for any type automatically, take a look: https://github.com/tidwall/hashmap/blob/e128c7c0599b6d15d68345d07dd373cf26c8904d/map.go#L45. This method uses the memory bytes directly to generate hash and Theine also use this. 

By the way do you find any bug or think something can be improved about Theine? Because it's not popular, I can see all star history on my home page.

**Comment by erni27** [comment]
Using `unsafe` and `reflect` packages is not an option in `imcache`. It conflicts with its origin design.

In general, I consider adding more default hashers with uniform distribution to `imcache` at least for simple types.

> By the way do you find any bug or think something can be improved about Theine? Because it's not popular, I can see all star history on my home page.

I'll take a look at your project once I have some time.

**Comment by Yiling-J** [comment]
Understood and let me close this issue. Star and unstar made me a little nervous if there is bugs I didn't know.
